version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=nest_postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - nest_network

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge